declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_OPENAI_API_KEY: string;
    NEXT_PUBLIC_OPENAI_ASSISTANT_ID_GENERAL: string;
    NEXT_PUBLIC_OPENAI_ASSISTANT_ID_CODING: string;
    NEXT_PUBLIC_OPENAI_ASSISTANT_ID_WRITING: string;
    NEXT_PUBLIC_OPENAI_ASSISTANT_ID_RESEARCH: string;
    NEXT_PUBLIC_OPENAI_ASSISTANT_ID_CREATIVE: string;
    NEXT_PUBLIC_OPENAI_ASSISTANT_ID_BUSINESS: string;
    NEXT_PUBLIC_SUPABASE_URL: string;
    NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
  }
} 